name: Run Renovate on PR Creation

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Renovate
        uses: renovatebot/github-action@v32.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
